import { atom } from "recoil";
import type { Employee } from "./searchResultState";

export const allEmployeeState = atom<Employee[]>({
  key: "allEmployeeState",
  default: [
    {
      employeeId: 1,
      profileImageUrl: "",
      employeeName: "김민준",
      departmentName: "경영지원팀",
      position: "매니저",
      isSelected: false,
    },
    {
      employeeId: 2,
      profileImageUrl: "",
      employeeName: "박서연",
      departmentName: "마케팅팀",
      position: "팀장",
      isSelected: false,
    },
    {
      employeeId: 3,
      profileImageUrl: "",
      employeeName: "이지은",
      departmentName: "영업팀",
      position: "사원",
      isSelected: false,
    },
    {
      employeeId: 4,
      profileImageUrl: "",
      employeeName: "정우성",
      departmentName: "개발팀",
      position: "선임",
      isSelected: false,
    },
    {
      employeeId: 5,
      profileImageUrl: "",
      employeeName: "최유진",
      departmentName: "디자인팀",
      position: "주니어",
      isSelected: false,
    },
    {
      employeeId: 6,
      profileImageUrl: "",
      employeeName: "강동원",
      departmentName: "인사팀",
      position: "과장",
      isSelected: false,
    },
    {
      employeeId: 7,
      profileImageUrl: "",
      employeeName: "김태희",
      departmentName: "경영기획팀",
      position: "부장",
      isSelected: false,
    },
    {
      employeeId: 8,
      profileImageUrl: "",
      employeeName: "이하늬",
      departmentName: "재무팀",
      position: "대리",
      isSelected: false,
    },
    {
      employeeId: 9,
      profileImageUrl: "",
      employeeName: "고수",
      departmentName: "홍보팀",
      position: "팀원",
      isSelected: false,
    },
    {
      employeeId: 10,
      profileImageUrl: "",
      employeeName: "송혜교",
      departmentName: "사업개발팀",
      position: "수석",
      isSelected: false,
    },
    {
      employeeId: 1,
      profileImageUrl: "",
      employeeName: "김민준",
      departmentName: "경영지원팀",
      position: "매니저",
      isSelected: false,
    },
    {
      employeeId: 2,
      profileImageUrl: "",
      employeeName: "박서연",
      departmentName: "마케팅팀",
      position: "팀장",
      isSelected: false,
    },
    {
      employeeId: 3,
      profileImageUrl: "",
      employeeName: "이지은",
      departmentName: "영업팀",
      position: "사원",
      isSelected: false,
    },
    {
      employeeId: 4,
      profileImageUrl: "",
      employeeName: "정우성",
      departmentName: "개발팀",
      position: "선임",
      isSelected: false,
    },
    {
      employeeId: 5,
      profileImageUrl: "",
      employeeName: "최유진",
      departmentName: "디자인팀",
      position: "주니어",
      isSelected: false,
    },
    {
      employeeId: 6,
      profileImageUrl: "",
      employeeName: "강동원",
      departmentName: "인사팀",
      position: "과장",
      isSelected: false,
    },
  ],
});
